name: Run tests on staging
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/github-script@v7
        id: my-script
        with:
          result-encoding: string
          script: |
            github.rest.issues.listForRepo({
              owner: 'legendecas',
              repo: 'github-action-test',
            });
